# Generated by Django 3.2.9 on 2021-11-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
